[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "advent-of-code-data==2.1.0",
    "copier==9.10.2",
    "graphviz>=0.21",
    "networkx>=3.5",
    "numpy>=2.3.3",
    "sympy>=1.14.0",
]
